apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: ai-task-platform
type: Opaque
stringData:
  JWT_SECRET: "k8s-prod-jwt-secret-key-32chars-minimum"
  REFRESH_TOKEN_SECRET: "k8s-prod-refresh-secret-key-32chars-minimum"
  REDIS_PASSWORD: ""
